# This is a basic workflow to help you get started with Actions

name: Docs-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    paths: docs/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          pip install mkdocs-material==6.1.4
          mkdocs build --strict
      - name: Push to gh-pages
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "pushing to gh-pages"
        
